// ---------------------------------------------------------------------------
// Session Store — Zustand v5
// ---------------------------------------------------------------------------
// Manages the active meditation session lifecycle: playback state, technique
// progression, AI-generated guidance queue, and post-session depth rating.
// ---------------------------------------------------------------------------

import { create } from "zustand";

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

/** A single timed guidance prompt generated by the AI session planner. */
export interface GuidancePrompt {
  /** Seconds from session start when this prompt should appear */
  time: number;
  /** The guidance text to display / speak */
  text: string;
  /** Duration in seconds to keep the prompt visible */
  duration: number;
}

/** Audio configuration for the session (from AI planner output). */
export interface SessionAudioConfig {
  binauralFreq: number;
  carrier: number;
  bpm: number | null;
  key: string | null;
  reverbDecay: number;
  noiseLevel: number;
}

/** The full AI-generated session plan. */
export interface SessionPlan {
  mode: "still" | "active";
  activeProfile: "drift" | "pulse" | "depth" | null;
  focusLevel: "sync" | "edge" | "expand" | "void";
  duration: number; // seconds
  techniques: string[]; // technique codes e.g. ["B-01", "S-03"]
  guidanceScript: GuidancePrompt[];
  audioConfig: SessionAudioConfig;
  reasoning: string;
}

/** Pre-session state check-in. */
export interface StateCheckIn {
  mood: string;
  energy: string;
  timeOfDay: string;
}

export interface SessionState {
  // --- Core session data ---
  /** The current session plan (null when no session is active) */
  currentSession: SessionPlan | null;
  /** Pre-session state check-in */
  stateBefore: StateCheckIn | null;

  // --- Playback ---
  isPlaying: boolean;
  isPaused: boolean;
  /** Elapsed time in seconds since session start */
  elapsed: number;

  // --- Technique progression ---
  /** Index into currentSession.techniques */
  currentTechniqueIndex: number;

  // --- Guidance ---
  /** Queue of guidance prompts yet to be shown */
  guidanceQueue: GuidancePrompt[];
  /** The prompt currently being displayed (null if none) */
  activeGuidance: GuidancePrompt | null;

  // --- Post-session ---
  /** 1-10 depth rating set after session ends */
  depthRating: number | null;
}

export interface SessionActions {
  /** Load a session plan and transition to ready state */
  startSession: (plan: SessionPlan, stateBefore?: StateCheckIn) => void;
  /** Pause the active session */
  pauseSession: () => void;
  /** Resume a paused session */
  resumeSession: () => void;
  /** End the session (completed or abandoned) */
  endSession: () => void;
  /** Advance elapsed time (called by a timer interval) */
  tick: (deltaSeconds: number) => void;
  /** Set the post-session depth rating */
  setDepthRating: (rating: number) => void;
  /** Advance to the next technique in the plan */
  nextTechnique: () => void;
  /** Push a new guidance prompt into the queue */
  addGuidance: (prompt: GuidancePrompt) => void;
  /** Set the currently displayed guidance (called by the guidance scheduler) */
  setActiveGuidance: (prompt: GuidancePrompt | null) => void;
  /** Full reset back to initial state */
  reset: () => void;
}

export type SessionStore = SessionState & SessionActions;

// ---------------------------------------------------------------------------
// Initial state
// ---------------------------------------------------------------------------

const initialState: SessionState = {
  currentSession: null,
  stateBefore: null,
  isPlaying: false,
  isPaused: false,
  elapsed: 0,
  currentTechniqueIndex: 0,
  guidanceQueue: [],
  activeGuidance: null,
  depthRating: null,
};

// ---------------------------------------------------------------------------
// Store
// ---------------------------------------------------------------------------

export const useSessionStore = create<SessionStore>()((set, get) => ({
  ...initialState,

  startSession: (plan, stateBefore) => {
    set({
      currentSession: plan,
      stateBefore: stateBefore ?? null,
      isPlaying: true,
      isPaused: false,
      elapsed: 0,
      currentTechniqueIndex: 0,
      guidanceQueue: [...plan.guidanceScript].sort((a, b) => a.time - b.time),
      activeGuidance: null,
      depthRating: null,
    });
  },

  pauseSession: () => {
    set({ isPlaying: false, isPaused: true });
  },

  resumeSession: () => {
    if (get().isPaused) {
      set({ isPlaying: true, isPaused: false });
    }
  },

  endSession: () => {
    set(initialState);
  },

  tick: (deltaSeconds) => {
    const state = get();
    if (!state.isPlaying || state.isPaused) return;

    const newElapsed = state.elapsed + deltaSeconds;
    const remaining: GuidancePrompt[] = [];
    let nextActive = state.activeGuidance;

    // Check if any queued prompts should fire
    for (const prompt of state.guidanceQueue) {
      if (prompt.time <= newElapsed) {
        nextActive = prompt;
      } else {
        remaining.push(prompt);
      }
    }

    // Clear active guidance if its display duration has passed
    if (
      nextActive &&
      newElapsed > nextActive.time + nextActive.duration
    ) {
      nextActive = null;
    }

    // Auto-end session when planned duration is reached
    const session = state.currentSession;
    if (session && newElapsed >= session.duration) {
      set({
        elapsed: session.duration,
        isPlaying: false,
        isPaused: false,
        guidanceQueue: remaining,
        activeGuidance: nextActive,
      });
      return;
    }

    set({
      elapsed: newElapsed,
      guidanceQueue: remaining,
      activeGuidance: nextActive,
    });
  },

  setDepthRating: (rating) => {
    const clamped = Math.max(1, Math.min(10, Math.round(rating)));
    set({ depthRating: clamped });
  },

  nextTechnique: () => {
    const state = get();
    const techniques = state.currentSession?.techniques;
    if (!techniques) return;
    const nextIndex = state.currentTechniqueIndex + 1;
    if (nextIndex < techniques.length) {
      set({ currentTechniqueIndex: nextIndex });
    }
  },

  addGuidance: (prompt) => {
    set((state) => ({
      guidanceQueue: [...state.guidanceQueue, prompt].sort(
        (a, b) => a.time - b.time,
      ),
    }));
  },

  setActiveGuidance: (prompt) => {
    set({ activeGuidance: prompt });
  },

  reset: () => {
    set(initialState);
  },
}));
